server:
  port: 8785
  
spring:
  application:
    name: ${eureka.application.names.config}
  profiles:
    active: native
  cloud:
    config:
      label: master
      server:
        native:
          searchLocations: classpath:config/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/