server: 
  port: 8781
  
spring:
  application:
    name: ${eureka.application.names.netty}
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
netty: 
  server:
    port: 29581


feign: 
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 40000
        readTimeout: 40000
  