server: 
  port: 8781
  
spring:
  application:
    name: product-netty-service
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
netty: 
  server:
    port: 29581


    